### ISSUE TITLE
make clear support at least direct on top of QUIC and on top of webtransport

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-charter#10]

**Comment by LPardue** [comment]
+1, miminizing references to lower layer primitives makes things easier to map

**Comment by aboba** [comment]
The information available in a WebTransport Javascript API is quite different from that available in media transport integrated tightly with QUIC. Trying to create a single solution that works in either case doesn't seem sensible to me. I'd focus on the browser use case.

**Comment by suhasHere** [comment]
closing this based on #34 and charter sync on 4/22
