### ISSUE TITLE
Need media container agility 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-charter#11]

**Comment by maxsharabayko** [comment]
If possible, might be worth considering being agnostic to the container itself, as long as it provides certain features that suit live ingest and distribution goals.
Signaling the media container and codecs being used in a connection can be done using SDP. The transport itself does not have to be aware of what exactly is inside.

**Comment by aboba** [comment]
There are scenarios where containers would be useful (e.g. DRM), and others where it adds no value (e.g. where decoding is handled via WebCodecs).  So it would be useful to be able to handle either case.

**Comment by suhasHere** [comment]
Closing this based on #34 and charter sync on 4/22
