### ISSUE TITLE
Need to support encrypted payloads 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-charter#13]

**Comment by fiestajetsam** [comment]
I'm guessing this is covering DRM as well as more privacy-focus encryption (such as end to end in a telephony use case). What should be clear is the scope of this and where certain responsibilities like key exchange, rotation, etc lie with. A protocol that doesn't solve it all will be ideal, but then the integration with existing patterns will be crucial. Also consider if there's a tie in with authentication (#14) - some protocols have tied the encryption key to a shared secret for simplicity, but I would vote we don't do it explicitly.

**Comment by aboba** [comment]
The threat model needs to be clearly defined. For streaming, where the video ingester is trusted to have access to cleartext media, the SFRAME/PERC threat model doesn't make sense.  DRM may be of interest, but today that implies containerization.  So there may be a need to define non-containerized DRM mechanisms for use with APIs such as WebCodecs.  However, there are also other threat models that don't fit into either the DRM or SFRAME/PERC buckets.

**Comment by fluffy** [comment]
I think the keying should be outside of MoQ other than to assume that there is keying and provide a way to tie it confidential and authenticity. This is largely to avoid the issue of trying to discuss DRM at the IETF. But it should be possible to encrypt the packets and have them distributed without knowing the keys. Clearly in many uses cases the streaming server would know the keys, but a relay may not know the keys to decode the DRM video and one can imagine some case where the distributed video could show it had not been changed from the ingest video. (clearly there are far more uses cases where is has to be changed for varios reason too)

**Comment by suhasHere** [comment]
closing based on the latest Prs
