### ISSUE TITLE
Need to say something about authentication 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-charter#14]
Even if some protocol outside of this has done the user authentication, we need a way to bind this channel to that authentication.

**Comment by jgh-twitch** [comment]
Just to piggyback on auth a little bit it's probably worth thinking about signalling more broadly - Auth, capabilities exchange, how do i push/pull, errors, extensibility

**Comment by suhasHere** [comment]
Closing based on the latest PRs
