### ISSUE TITLE
Can you define prioritization any better?

### ISSUE THREAD

**Issue by LPardue** [moq-wg/moq-charter#27]
This term is ambiguous and overloaded. What does the charter think it is putting in scope and do people agree with that definition?

I.e. is it a way to prioritize sending data, or a way to signal to a peer what you want prioritized, or a way to signal to a relay how it should send, etc

**Comment by suhasHere** [comment]
Good points . Agree we need to make it more clear and I feel it applies to mix of the contexts above

, I see it as a way to indicate  intermediaries (relays or origin if it is forwarding as well) to make drop decision or pick the data when forwarding under congestion or making caching decisions. 

The same when is input via an API at the sender client to tell stack to choose the right stream.

Some examples might be
- audio is more important than video or other data
- In layered codec, base layer is more important than enhancement

**Comment by LPardue** [comment]
Since this is predominantly a push oriented interaction, these considerations seem reasonable. 

Perhaps we can succinctly expand the description to something like

"An interoperable way to signal the priority of media from source to destination" 

And 

"A strategy for prioritized dispatch of concurrently available media"

?

**Comment by fluffy** [comment]
I like the way you are going on phrasing this. I viewed it as a way of the the application to signal it's intent to the things that dropped media of what order to drop and send media.

**Comment by kixelated** [comment]
In order to keep latency low, there needs to be a rapid response to congestion. Prioritization is one such mechanism because it designates that some media should be dropped or starved during congestion. However, it's not the only approach, and it would be perfectly feasible to use media over QUIC without prioritization. For example, the encoder could just adjust the bitrate in response to congestion.

**Comment by kixelated** [comment]
What I'm trying to say is that prioritization is optional and depends on the protocol/implementation, and I don't think it needs to be in the charter.

**Comment by LPardue** [comment]
Good point Luke. We might generalize the statement further to something like "The media protocol will contain considerations for effective use of available sending capacity (for example, adjustment of media quality based on congestion window, prioiritizated dispatch of concurrently available media, etc).

**Comment by kixelated** [comment]
Yeah, effectively some form of congestion control at the media layer, either by dropping parts of the media stream or adjusting the encoded bitrate.

**Comment by suhasHere** [comment]
#23  talks about rate control at the encoder to go up/down the bitrate. Such feedback is necessary. 
Prioritization also serves 2 roles 
1. Enabling Application to indicate  its preference 
2.  For intermediaries or services at origin that wish to make a forward/drop choice especially under constrained network conditions

1) is more of an API definition but 2) is part of the  protocol.

in summary I do feel, a way for congestion status feedback to encoder as well as  a way for for intermediaries to help make better decisions will be useful.

**Comment by suhasHere** [comment]
closing based on the latest PRs
