### ISSUE TITLE
"a way to name and request media"

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-charter#29]
> The work focuses on two main areas: A common media publication protocol, and a way to name and request media.

I don't think these areas are clearly defined or delimited. I'm struggling to figure out why certain requirements are in one area but not the other.

For example, why is "an interoperable way to request media and encodings" part of the media publication protocol, but "Selection of desire encoding ( choosing language, bit rate , etc )" considered a way to name and request media? They seem like the same thing to me.

**Comment by suhasHere** [comment]
> > The work focuses on two main areas: A common media publication protocol, and a way to name and request media.
> 
> I don't think these areas are clearly defined or delimited. I'm struggling to figure out why certain requirements are in one area but not the other.
> 
> For example, why is "an interoperable way to request media and encodings" part of the media publication protocol, but "Selection of desire encoding ( choosing language, bit rate , etc )" considered a way to name and request media? They seem like the same thing to me.

@kixelated  "an interoperable way to request media and encodings" is common across media ingest and distribution. That section of the charter talks about both.

Later section highlights aspects of request for qualities and other things too.

**Comment by suhasHere** [comment]
> I think you're trying to split out the areas based on the QuicR architecture, but the charter should not assume a specific architecture (or even the existence of two protocols). Relay support should be listed as a requirement in the charter instead.

@kixelated 
the charter currently specifies relay as below

```The MOQ architecture allows for the use of optional relays as first class elements of the design. The media publication protocol can leverage on-path relays/caches wherever applicable to improve the media quality```

do you think we need to be more explicit or a better rewording is preferred ? please let me know
