### ISSUE TITLE
Protocol, container and API standardization

### ISSUE THREAD

**Issue by aboba** [moq-wg/moq-charter#30]
For video ingestion, the case for protocol standardization seems solid - distinct implementations (e.g. mobile, browser, server) need to interoperate. 

For media distribution to a browser, the case for protocol standardization seems more fuzzy.  Assuming the Web APIs (e.g. WebTransport, WebCodecs, MSE, etc.) are implemented in an interoperable way between browsers, and the container formats assumed by the APIs are well defined, what aspects of the protocol need to be standardized and why? 

I'd note that WebRTC datachannel is today very widely used for media distribution (particularly in cloud gaming) without an apparent need for standardization of the application protocols.  Instead, the focus has been on standardization of the APIs and container formats. Why is QUIC different?

**Comment by jgh-twitch** [comment]
I don't think that the service and the player are the same entity is a safe assumption necessarily. There are a bunch of player vendors that don't have an associated service, and there are services that work with 3rd party players (such as IVS).

**Comment by kixelated** [comment]
Yeah I was going to say the exact same thing.

There are many services that offer HLS/DASH endpoints and expect you to use your own player. In fact that's kind of the point; it's easy to host the media files via a commodity CDN and watch via some arbitrary player (ex. hls.js, VLC, exoplayer, avplayer).

**Comment by suhasHere** [comment]
Propose to change the charter text - omit the word container, replace with media format
