### ISSUE TITLE
Are either of the "two main areas" useful without the other main area?

### ISSUE THREAD

**Issue by SpencerDawkins** [moq-wg/moq-charter#31]
On 

> The work focuses on **two main areas**: A common media publication protocol, and a way to name and request media

If we had only one of these, but not both, would having one of these solve any problems that aren't solved today?

I'm mostly asking about whether we agree that both are required, and it's OK if they fate-share in a single charter proposal that is either accepted or rejected.

**Comment by jgh-twitch** [comment]
I think if the "a way to name and request media" is not solved then we will have a situation like WebRTC where everybody has their own signalling solution and implementations aren't incompatible and in 5 years someone is creating a WHIP-like working group for this protocol.

**Comment by suhasHere** [comment]
I tend to agree with @jgh-twitch. Naming things will enable an interoperable and predictable way to push or pull the media. Today in streaming world it is done via file name for segments in the GET. We need to allow that to work as well as allow moq applications to uniformly address the media.

**Comment by suhasHere** [comment]
Ted " The work focuses on two main areas: A common media publication protocol, and ways to identify and interact with the media"  ..

**Comment by suhasHere** [comment]
fixed in #31 based on 5/13 sync
