### ISSUE TITLE
Suggested Label for "Charter"

### ISSUE THREAD

**Issue by SpencerDawkins** [moq-wg/moq-charter#32]
We have (checks upper left corner of repo) 20 open issues now, and we are still adding more. 

I agree that we have useful issues that may not need to be resolved before we can submit a charter, but they are still useful 

It might be useful to tag the issues that we expect to be reflected in the proposed charter, so we can focus on them between now and IETF 114. 

@suhasHere divided the issues we had as of yesterday into three groups ("small", "medium", "large"). That might be useful to capture in labels as well.

**Comment by suhasHere** [comment]
closing this issue as it is procedural.
