### ISSUE TITLE
"This working group will not propose changes to underlying QUIC transport, but ..."

### ISSUE THREAD

**Issue by SpencerDawkins** [moq-wg/moq-charter#5]
I agree that changes to underlying QUIC transport are out of scope, and they should be. On the other hand, I am pretty sure that we already know about some QUIC EXTENSIONS that would be very helpful. 

If we wanted to start a list of extensions that we're pretty sure we'll need, that would be useful to keep written down. 

I'm thinking of signaling to say "I'm expecting SCREAM and if you do BBRv2, that's gonna be really bad", for one example of a needed extension. We won't die without it, but if the goal is to outperform what people are doing now so they have an incentive to switch, that will be a lot easier if we have it. 

Other people may be thinking of other helpful extensions.

**Comment by fluffy** [comment]
Thoughts on what we should change in charter for this one ?

**Comment by SpencerDawkins** [comment]
@fluffy - I think this text has already changed since I commented on it (I was typing issues during our Thursday post-BOF session, which seems like a lifetime ago. 

But I'm now seeing

> This working group will not propose changes to underlying QUIC transport, but may propose requirements to the QUIC WG for things such as extensions to congestion control algorithms. 

I think this would be better as 

> This working group will not propose changes to underlying QUIC transport, but may propose requirements to the QUIC WG for things such as extensions to allow **selection of** congestion control algorithms. 

A QUIC peek at the QUIC charter still says 

> **Defining new congestion control schemes is explicitly out of scope for the WG**. However, new QUIC extensions that support development and experimentation with new congestion control schemes may fall under the third work area.

It seems useful to change our proposed charter text so that it's clear we aren't asking QUIC to do anything with congestion control mechanisms, except to provide a mechanism to select among them.

**Comment by SpencerDawkins** [comment]
@acbegen - I'm sympathetic to this theory, but if we don't have any way to tell the QUIC peer that we're doing "media" (whatever that means), we'll get the default QUIC behavior, which is likely to be CUBIC or BBR, either of which would not be a good thing. 

You've correct in saying that a QUIC sender can go as crazy as it wants to, but [QUIC flow control ](https://www.rfc-editor.org/rfc/rfc9000.html#name-flow-control)gets the last vote on whether when a packet can be sent. What I'm saying is that we may want/need to tell the QUIC peer "don't do that, do something that might be reasonable for media". 

Does that make sense?

**Comment by LPardue** [comment]
The specific text

> may propose requirements to the QUIC WG for things such as extensions to congestion control algorithms

needs to change. The QUIC WG won't be extending CC. Perhaps you mean extensions to support $stuff to do with CC, like making more information  available to them - that would be more feasible.

**Comment by acbegen** [comment]
> @acbegen - I'm sympathetic to this theory, but if we don't have any way to tell the QUIC peer that we're doing "media" (whatever that means), we'll get the default QUIC behavior, which is likely to be CUBIC or BBR, either of which would not be a good thing.

True, but if the sender knows what it is sending, it can make the right choice (and I guess the receiver knows what it is supposed to receive anyway).

> You've correct in saying that a QUIC sender can go as crazy as it wants to, but [QUIC flow control ](https://www.rfc-editor.org/rfc/rfc9000.html#name-flow-control)gets the last vote on whether when a packet can be sent. 

How do we know that whoever can trick CC won't trick flow control? This is all in the application space.

> What I'm saying is that we may want/need to tell the QUIC peer "don't do that, do something that might be reasonable for media".
> 
> Does that make sense?

**Comment by SpencerDawkins** [comment]
@LPardue - please check my comment above yours - @acbegen  was responding to that just below your comment. 

I think you and I agree on everything but the details of what might be in scope for the QUIC working group.

**Comment by LPardue** [comment]
The only CC algorithm that QUIC defined is a NewReno type thing, that is not used in deployments that care about performance. Extending that algorithm seems like a waste of effort. 

Giving the QUIC WG requirements to extend algorithms it doesn't own seems like a wrong layer of indirection to me. Rather the requirements in MoQ might identify algorithm changes, which in turn generate requirements on the QUIC transport. That form of dependency is reasonable; work to extend or change QUIC is suitable for the QUIC WG.

**Comment by SpencerDawkins** [comment]
@LPardue - I'm sorry, I'm not being clear about this. 

My understanding of what QUIC was chartered to do, was to specify a baseline congestion controller, and IIRC, the baseline congestion controller was originally constrained as follows (quoting from https://datatracker.ietf.org/doc/charter-ietf-quic/01/)

> Work on congestion control will describe use of a **standardized congestion controller as a default scheme** for QUIC.

That was, at the time, basically NewReno. 

The assumption was that if QUIC implementations supported the default scheme, that would be "safe", and that if a QUIC sender supported a "better" congestion controller than NewReno, the QUIC sender was free to use that. 

Are we together, so far?

What we're talking about here, is not designing a new congestion controller that would be better-behaved for media in MOQ, and not asking the QUIC working group to design a new congestion controller for MOQ. 

What we are talking about, is asking the QUIC working group to provide an extension that says something like "don't use congestion controllers that probe for additional bandwidth until they encounter loss, because we're not trying to saturate available path bandwidth, and probing that introduces jitter isn't helping us". 

Obviously, the devil is in the details, but does that sound more coherent?

**Comment by LPardue** [comment]
Thanks for clarification Spencer. That makes sense.

I'm not totally convinced such a thing as preferred CC signalling to a peer is needed, or would work. But that's just my 2c. Keeping in scope the _possibility_ to investigate that in this WG seems reasonable to me at least. 

We don't need to solutionize here. But the answer likely comes down to, what is the latest opportunity for a RFC9000 sender to pick a CC algorithm for a negotiated connection? You can work backwards from that to see if existing mechanisms could work. For instance, if ALPN selected "moq" or whatever we call this thing, that might be enough; and the QUIC WG wouldn't need to spend any effort. If you need something later, e.g. post-handshake - the options and outcomes broaden. So drilling down on those would seem good work for the MoQ WG.

**Comment by SpencerDawkins** [comment]
Thank you for the clarification, Lucas!

**Comment by fluffy** [comment]
@SpencerDawkins - Is a PR needed for this? Could you make one?

**Comment by SpencerDawkins** [comment]
@fluffy - I think a PR to remove the bogus example is needed. I linked a proposed PR to this issue.

**Comment by fluffy** [comment]
+1 to merging spencers PR - i like it.
