### ISSUE TITLE
How to map media ontop of quic 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-charter#8]
Should probably use a phase ike "how to map media onto quic" in the charter. 

This mapping may be  different for different container formats.

**Comment by LPardue** [comment]
this seems to be related to #26 IMO and I would address them at the same type.

**Comment by fluffy** [comment]
I think this is a duplicate of #26 so propose just closing this one.

**Comment by suhasHere** [comment]
closing this based on charter sync on 4/22 and PR #34
